spring.application.name: ProductionNetsProxy
upstream:
  ips: "127.0.0.1:8081,127.0.0.1:8082"
timeout:
  connection: 1
  response: 3
#server.ssl.key-store: /app/keystore/keys.p12
#server.ssl.key-store-password: password
#server.ssl.key-store-type: PKCS12
#server.ssl.key-alias: mysslkey